M48
; DRILL file {KiCad 8.0.8} date 2025-02-03T08:14:25-0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-03T08:14:25-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X2.2236Y-3.1634
X2.2236Y-3.3913
T2
X2.1553Y-5.1849
X2.1553Y-5.4989
M30
